spring.application.name=jpa-hibernate
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
springdoc.model-and-view-allowed=false
logging.level.org.springframework.security=DEBUG
#Dice ad hibernate di aspettare l'esecuzione degli script sql e poi dopo gli script cercare le entity
springdoc.override-with-generic-response=true